default libvirtd network: three small fixes
 - use bash device /dev/tcp/{ip}/{port} to avoid dependency on iputils-ping
 - fail if no free network can be found
 - use tighter regex to replace IP address to avoid finding "122"
   elsewhere in the xml (for example in the uuid)

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -14,8 +14,16 @@ stages:
     - export
     # In case there is an underlying network already with the same network address, e.g. a runner
     # running on top of a libvirtd VM, we need to look for another network
-    - apt-get update ; apt-get install -y iputils-ping
-    - for n in $(seq 122 129) ; do ping -c 1 192.168.${n}.1 || { UNDERLYING_NET=${n} ; break; } ; done
+    - |
+        UNDERLYING_NET=0
+        for n in $(seq 122 129); do
+          bash -c "echo >/dev/tcp/192.168.${n}.1/22" \
+            || { UNDERLYING_NET=${n} ; break; }
+        done
+        if [ "$UNDERLYING_NET" -eq 0 ]; then
+          echo "unable to find an unused network" >&2
+          exit 1
+        fi
     - |
         cat >/etc/lxc/default.conf <<EOT
         lxc.net.0.type = veth
@@ -42,7 +50,7 @@ stages:
         if [ "$UNDERLYING_NET" -ne 122 ] ; then
           virsh net-destroy default || true
           virsh net-dumpxml default > /tmp/default.xml
-          sed -i -e "s/122/${UNDERLYING_NET}/g" /tmp/default.xml
+          sed -i -e "s/='192\.168\.122\.\([0-9]\+\)'/='192.168.${UNDERLYING_NET}.\1'/g" /tmp/default.xml
           virsh net-undefine default
           virsh net-define /tmp/default.xml
         fi
